package constants

const (
	MONGO_DB_NAME_DEV         = "playoffBracketsDev"
	MONGO_DB_NAME_PROD        = "playoffBracketsProd"
	STANDINGS_COLLECTION_NAME = "standings"
	USERS_COLLECTION_NAME     = "users"
	GAMES_COLLECTION_NAME     = "games"
	BRACKETS_COLLECTION_NAME  = "brackets"

	ENV                     = "ENV"
	MONGO_DB_CONNECTION_ENV = "NFLPLAYOFFDBSECRET"
	JWT_KEY_ENV             = "NFLPLAYOFFJWTKEY"
	PORT_ENV                = "PORT"

	ENV_DEV   = "dev"
	ENV_TEST  = "test"
	ENV_STAGE = "stage"
	ENV_PROD  = "prod"

	DOMAIN_LOCAL  = "localhost"
	DOMAIN_DOCKER = "0.0.0.0"

	COOKIE_TOKEN = "playoff_bracket_token"

	CARDINALS   = "Cardinals"
	FALCONS     = "Falcons"
	RAVENS      = "Ravens"
	BILLS       = "Bills"
	PANTHERS    = "Panthers"
	BEARS       = "Bears"
	BENGALS     = "Bengals"
	BROWNS      = "Browns"
	COWBOYS     = "Cowboys"
	BRONCOS     = "Broncos"
	LIONS       = "Lions"
	PACKERS     = "Packers"
	TEXANS      = "Texans"
	COLTS       = "Colts"
	JAGUARS     = "Jaguars"
	CHIEFS      = "Chiefs"
	RAMS        = "Rams"
	CHARGERS    = "Chargers"
	RAIDERS     = "Raiders"
	DOLPHINS    = "Dolphins"
	VIKINGS     = "Vikings"
	PATRIOTS    = "Patriots"
	SAINTS      = "Saints"
	GIANTS      = "Giants"
	JETS        = "Jets"
	EAGLES      = "Eagles"
	STEELERS    = "Steelers"
	SEAHAWKS    = "Seahawks"
	FORTYNINERS = "49ers"
	BUCCANEERS  = "Buccaneers"
	TITANS      = "Titans"
	COMMANDERS  = "Commanders"

	AFC = "AFC"
	NFC = "NFC"
)
